### ISSUE TITLE
Clarification: Do you need to install the wireguard native package on the server and clients?

### ISSUE THREAD

**Issue by Darin755** [openwisp/ansible-wireguard-openwisp#42]
So I was trying to get Wireguard working and I managed to get everything setup in the web interface and I applied the playbook. However it didn't work and I noticed that wireguard wasn't installed or configured on the server or the client. 

Do I need to install it manually? Right not I'm using netbird so its not a big deal but I would like to look into updating the docs if additional steps are required.

**Comment by nemesifier** [comment]
Wireguard is not installed by default on OpenWrt so you need to install it there or modify your firmware build to include it.
This playbook does install the wireguard dependencies on the server.

**Comment by Darin755** [comment]
Good to know, Thanks.

Maybe that should be added to the documentation?

**Comment by nemesifier** [comment]
> Good to know, Thanks.
> 
> Maybe that should be added to the documentation?

I just added a note at the beginning of each VPN tutorial:
https://github.com/openwisp/openwisp-controller/commit/9bf5d48a174cf80dc1728aff7b56063c0d5141c8.

Let me know if you think more action is needed.
